import winreg
import datetime
import codecs
import struct
from dev_tools.debug_flags import DEV_MODE, FORCE_REFRESH_SNAPSHOT
from dev_tools.usage_snapshot import save_snapshot, load_snapshot, snapshot_exists

USERASSIST_PATH = r"Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist"


# ----------------- CLEANING RULES -----------------

SKIP_PATTERNS = [
    # registry noise
    "ueme_", "autogenerated",
    # uwp garbage IDs
    "immersivecontrolpanel", "xboxgamingoverlay",
    "screensketch", "snipping", "screenshot",
    # specific app blacklist
    "crx_", ".crx", "kingsoft", "prometheus",
    # generic junk signals
    "!app", "8wekyb3d8bbwe", "_cw5n1h2txyewy",
    "omen", "omenlightstudio", "lightstudio", "hp.omen",
    # system tools not geneally using apps
    "regedit", "registry editor", "photolaunch", "services.msc",
    "mmc", "osk", "on-screen keyboard", "autohotkey_",
     # "stickynotes", "microsoftstickynotes",
    "powertoys", "setup", "usersetup",
    "autohotkey.autohotkey", "lighstudio-ui", "codex"
]

MERGE_GROUPS = {
    "Chrome":         ["chrome", "browser"],
    "YouTube":        ["youtube", "yt", "Youtube", "You tube"],
    "Brave":          ["brave"],
    "File Explorer":  ["explorer", "file explorer"],
    "WhatsApp":       ["whatsapp"],
    "Notepad":        ["notepad"],
    "CMD":            ["cmd.exe", "command prompt", "cmd"],
    "PyCharm":        ["pycharm"],
    "Wise Memory":    ["wisememory", "wise memory"],
    "Task Manager":   ["taskmgr", "task manager"],
    "VAP":            ["vap"],
    "Telegram":       ["telegram"],
    "VLC":            ["vlc"],
    "Arduino":        ["arduino"],
    "PowerShell":      ["powershell", "Windows PowerShell"],
    "Calculator":     ["calculator", "calc"],
    "ChatGPT": ["chatgpt (ashish)", "chatgpt"],
    "Claude":  ["claude (ashish)", "claude"],

}


# ----------------- HELPERS -----------------

def parse_filetime(data, offset=60):
    try:
        ft = struct.unpack("<Q", data[offset:offset + 8])[0]
        if ft == 0:
            return None
        EPOCH_DIFF = 116444736000000000
        timestamp = (ft - EPOCH_DIFF) / 10_000_000
        if timestamp < 0:
            return None
        return datetime.datetime.fromtimestamp(timestamp)
    except:
        return None


def extract_app_name(decoded):
    # strip path — keep only filename
    if "\\" in decoded:
        decoded = decoded.split("\\")[-1]

    # strip .lnk shortcuts
    if decoded.lower().endswith(".lnk"):
        decoded = decoded[:-4]

    # strip .exe extension
    if decoded.lower().endswith(".exe"):
        decoded = decoded[:-4]

    # handle UWP pattern: Publisher.AppName_version!App
    if "!" in decoded and "_" in decoded:
        name = decoded.split("!")[0]       # take left of !
        name = name.split("_")[0]          # strip version suffix
        if "." in name:
            name = name.split(".")[-1]     # take last part of publisher.name
        decoded = name

    return decoded.strip()


def should_skip(name):
    name_lower = name.lower()

    # skip if contains any skip pattern
    if any(p in name_lower for p in SKIP_PATTERNS):
        return True

    # skip raw UWP IDs that slipped through (contain _ and ! or long hex-like strings)
    if "_" in name and ("!" in name or len(name) > 40):
        return True

    # skip very short names (single letters, just .exe leftovers)
    if len(name.strip()) <= 2:
        return True

    return False


def apply_merge(name):
    name_lower = name.lower()
    for group_label, patterns in MERGE_GROUPS.items():
        if any(p in name_lower for p in patterns):
            return group_label
    return name


# ----------------- CORE ENGINE -----------------

def get_usage_data(days=7):
    apps = {}

    try:
        ua_key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, USERASSIST_PATH)
    except FileNotFoundError:
        return {}

    i = 0
    while True:
        try:
            guid = winreg.EnumKey(ua_key, i)
            count_path = USERASSIST_PATH + f"\\{guid}\\Count"

            try:
                count_key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, count_path)
                j = 0

                while True:
                    try:
                        name, data, _ = winreg.EnumValue(count_key, j)
                        decoded = codecs.decode(name, "rot_13")

                        # skip registry noise entries
                        if decoded.startswith("UEME_") or len(data) != 72:
                            j += 1
                            continue

                        run_count = struct.unpack("<I", data[4:8])[0]
                        last_run = parse_filetime(data, offset=60)

                        if run_count == 0:
                            j += 1
                            continue

                        # clean the name
                        app_name = extract_app_name(decoded)

                        # skip garbage
                        if should_skip(app_name):
                            j += 1
                            continue

                        # merge duplicates into clean group names
                        app_name = apply_merge(app_name)

                        # accumulate
                        if app_name in apps:
                            apps[app_name]["count"] += run_count
                            if last_run and (
                                apps[app_name]["last_run"] is None
                                or last_run > apps[app_name]["last_run"]
                            ):
                                apps[app_name]["last_run"] = last_run
                        else:
                            apps[app_name] = {
                                "count": run_count,
                                "last_run": last_run
                            }

                    except OSError:
                        break

                    j += 1

            except FileNotFoundError:
                pass

        except OSError:
            break

        i += 1

    # apply 7-day window filter
    now = datetime.datetime.now()
    cutoff = now - datetime.timedelta(days=days)

    # ... inside the function ...
    # ------------------------
    # FINAL FILTERED DATA
    # ------------------------
    filtered_data = {
        name: info for name, info in apps.items()
        if info["last_run"] and info["last_run"] >= cutoff
    }

    # FOR THE CONFIRMATION OF THE DEV MODE
    # print("DEV MODE ACTIVE:", DEV_MODE)
    # print("USAGE DATA:", filtered_data)

    # ------------------------
    # DEV MODE HANDLING
    # ------------------------
    if DEV_MODE:

        # force fresh snapshot
        if FORCE_REFRESH_SNAPSHOT or not snapshot_exists():
            save_snapshot(filtered_data)
            return filtered_data

        # use snapshot instead of real data
        snapshot = load_snapshot()

        # print("LOADED SNAPSHOT:", snapshot)  # 👈 ADD THIS

        if snapshot:
            # FOR GETTING CONFIRMATION OF SOURCE
            # print("SOURCE:", "SNAPSHOT" if DEV_MODE else "REGISTRY")
            return snapshot

    # ------------------------
    # NORMAL FLOW
    # ------------------------
    # print("SOURCE:", "REGISTRY")  # 👈 ADD BEFORE FINAL RETURN
    # print("SOURCE:", "SNAPSHOT")
    return filtered_data

